use Velocity;

drop table NamedBankingProductAttribute;



create table NamedBankingProductAttribute
(
	id int primary key identity,
	BPAID int not null,
	Description nvarchar(200) not null,
	section nvarchar(50)  null,
)
;

SET IDENTITY_INSERT [dbo].[NamedBankingProductAttribute] ON 

INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (1, 1, N'Instrument identification code', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (2, 2, N'Instrument ISIN', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (3, 3, N'Internal Instrument Identifier', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (4, 4, N'Instrument type', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (5, 5, N'OTC ISIN', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (6, 6, N'Notional amount', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (7, 7, N'Notional amount type', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (8, 8, N'Notional currency 1', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (9, 9, N'Price', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (10, 10, N'Price type', N's1')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (11, 11, N'Yield', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (12, 12, N'Price currency', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (13, 13, N'Price Notation', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (14, 14, N'Publication date time', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (15, 15, N'No of contracts', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (16, 16, N'Lot size', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (17, 17, N'Multiplier', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (18, 18, N'Quantity', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (19, 19, N'Trading Date Time', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (20, 20, N'Trade Capture / Entry / Saved Time', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (21, 21, N'Trade Last Updated or Trade Modified Timestamp', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (22, 22, N'USI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (23, 23, N'UTI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (24, 24, N'Venue assigned ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (25, 25, N'SCB Internal Unique ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (26, 26, N'RFQ ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (27, 27, N'Order ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (28, 28, N'All IDs and System/Venue Name (key-value pairs)', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (29, 29, N'Intended to Clear indicator', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (30, 30, N'Clearing House/CCP or Exchange Name', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (31, 31, N'Clearing House or Exchange Trade Identifier - Type & Values', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (32, 32, N'Clearing Mandatory Flag', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (33, 33, N'TP System Venue ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (34, 34, N'ISO 10383 Segment MIC', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (35, 35, N'ISO 10383 Operating MIC', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (36, 36, N'Instrument SI Status', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (37, 37, N'Flag indicating Instrument is admitted to trading or traded on a trading venue', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (38, 38, N'Internal SCB Entity', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (39, 39, N'Venue of Publication', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (40, 40, N'Notation of the quantity in measurement unit', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (41, 41, N'Quantity Amount', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (42, 42, N'Reference period', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (43, 43, N'Type', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (44, 44, N'TP trade status', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (45, 45, N'USI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (46, 46, N'UTI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (47, 47, N'Venue assigned ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (48, 48, N'SCB Internal Unique ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (49, 49, N'RFQ ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (50, 50, N'Order ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (51, 51, N'All IDs and System/Venue Name', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (52, 52, N'Venue assigned ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (53, 53, N'Type of order', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (54, 54, N'Unassigned', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (55, 55, N'Transaction Reference Number', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (56, 56, N'Unassigned', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (57, 57, N'Order ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (58, 58, N'SCB Booking Entity/Branch', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (59, 59, N'Executing entity identification code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (60, 60, N'Sales/Marketer - RM PSID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (61, 61, N'Investment Firm covered by Directive 2014/65/EU', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (62, 62, N'Submitting entity identification code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (63, 63, N'Buyer identification code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (64, 64, N'SCB Booking Entity/Branch/LEI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (65, 65, N'CCP Name', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (66, 66, N'CCP LEI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (67, 67, N'Cpty Code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (68, 68, N'Cpty LEI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (69, 69, N'Cpty National ID for Natural Persons', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (70, 70, N'Block/Allocation Identifiers', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (71, 71, N'Buyer/Seller of Instrument', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (72, 72, N'Long/Short Indicator', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (73, 73, N'Fixed Rate Payer/Receiver Party', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (74, 74, N'Spread Payer/Receiver Party', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (75, 75, N'SCB Booking Entity/Branch', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (76, 76, N'SCB Booking Entity/Branch Country Code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (77, 77, N'Cpty Code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (78, 78, N'Cpty Country Code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (79, 79, N'Buyer/Seller Indicator', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (80, 80, N'Sales / Marketer PS ID ', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (81, 81, N'Cpty Code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (82, 82, N'Cpty First Name', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (83, 83, N'Cpty Code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (84, 84, N'Cpty Last Name', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (85, 85, N'Cpty code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (86, 86, N'Cpty date of birth', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (87, 87, N'Cpty Decision Maker ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (88, 88, N'Cpty LEI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (89, 89, N'Cpty National ID for Natural Persons', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (90, 90, N'Power Of Representation Flag', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (91, 91, N'Buyer Decision Maker ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (92, 92, N'Buyer Decision Maker First Name', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (93, 93, N'Cpty Decision Maker ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (94, 94, N'Buyer decision maker - Surname(s)', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (95, 95, N'Cpty Decision Maker ID', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (96, 96, N'Buyer decision maker - date of birth', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (97, 97, N'Seller identification code', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (98, 98, N'CCP Name', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (99, 99, N'Cpty Code', N's2')
GO
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (100, 100, N'Cpty LEI', N's2')
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (101, 101, N'Block/Allocation Identifiers', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (102, 102, N'Buyer/Seller of Instrument', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (103, 103, N'Long/Short Indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (104, 104, N'Fixed Rate Payer/Receiver Party', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (105, 105, N'Spread Payer/Receiver Party', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (106, 106, N'Country of the branch for the seller', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (107, 107, N'Seller - first name(s)', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (108, 108, N'Seller - surname(s)', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (109, 109, N'Seller - date of birth', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (110, 110, N'Seller - decision maker code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (111, 111, N'Sell decision maker - First Name(s)', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (112, 112, N'Sell decision maker - Surname(s)', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (113, 113, N'Sell decision maker - Date of birth', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (114, 114, N'Transmission of order indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (115, 115, N'SCB Booking Entity/Branch', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (116, 116, N'SCB Booking Entity/Branch/LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (117, 117, N'Cpty Code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (118, 118, N'Cpty LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (119, 119, N'SCB Booking Entity/Branch', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (120, 120, N'SCB Booking Entity/Branch/LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (121, 121, N'Cpty code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (122, 122, N'Cpty LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (123, 123, N'Trading date time', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (124, 124, N'Instrument SI Status', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (125, 125, N'Broker ID/Code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (126, 126, N'Agency vs Principal Model trade', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (127, 127, N'Quantity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (128, 128, N'Quantity currency', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (129, 129, N'Notional Amount at leg /Trade level', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (130, 130, N'Original/Amended Notional', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (131, 131, N'Trade Status/Event Type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (132, 132, N'Trade Link ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (133, 133, N'Effective Date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (134, 134, N'Notional Increase/Decrease Flag', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (135, 135, N'Price', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (136, 136, N'Price type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (137, 137, N'Price currency', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (138, 138, N'Clean Price', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (139, 139, N'Notional', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (140, 140, N'Accrued Coupon', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (141, 141, N'Settlement Amount', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (142, 142, N'Start cash', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (143, 143, N'End cash', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (144, 144, N'Venue ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (145, 145, N'Order Validity period', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (146, 146, N'Unassigned', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (147, 147, N'Unassigned', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (148, 148, N'Unassigned', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (149, 149, N'Internal SCB Entity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (150, 150, N'SCB Booking Entity/Branch', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (151, 151, N'SCB Booking Entity/Branch Country Code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (152, 152, N'Sales/Marketer PSID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (153, 153, N'Upfront Payment', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (154, 154, N'Premium Payer / Receiver', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (155, 155, N'Fees', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (156, 156, N'Fee Payer / Receiver', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (157, 157, N'Up-front payment currency', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (158, 158, N'Fees ccy', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (159, 159, N'Structure ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (160, 160, N'Package ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (161, 161, N'Link ID/Contract ID/Lifetime ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (162, 162, N'Instrument ISIN', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (163, 163, N'Internal Instrument Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (164, 164, N'Instrument Type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (165, 165, N'OTC ISIN', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (166, 166, N'Instrument Full Name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (167, 167, N'Instrument classification', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (168, 168, N'Notional currency 1', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (169, 169, N'Notional currency 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (170, 170, N'Price Multiplier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (171, 171, N'Underlying instrument code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (172, 172, N'Underlying index name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (173, 173, N'Duration / Term / Tenor of the Contract', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (174, 174, N'Frequency / Tenor at Leg Level', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (175, 175, N'Option type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (176, 176, N'Strike price', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (177, 177, N'Strike Price Currency', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (178, 178, N'Option exercise style', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (179, 179, N'Maturity Date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (180, 180, N'Expiry date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (181, 181, N'Delivery type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (182, 182, N'Algo ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (183, 183, N'Algo name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (184, 184, N'TP Sales ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (185, 185, N'Sales/Marketer PSID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (186, 186, N'TP Trader ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (187, 187, N'Investment decision within firm', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (188, 188, N'Country of the branch responsible for  the person  making the investment decision', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (189, 189, N'Execution within firm', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (190, 190, N'Country of the branch supervising the person responsible for the execution', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (191, 191, N'Waiver indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (192, 192, N'Short Selling Indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (193, 193, N'Trade Status', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (194, 194, N'Commodity Derivative Indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (195, 195, N'TP Product Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (196, 196, N'GiveUp/GiveIn Indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (197, 197, N'Portfolio compression indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (198, 198, N'Portfolio compression link ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (199, 199, N'Venue Type', NULL)
GO
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (200, 200, N'Trading Platform', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (201, 201, N'Venue Name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (202, 202, N'Counterparty MiFID Classification', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (203, 203, N'Market Segment Name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (204, 204, N'ISO 10383 Segment MIC', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (205, 205, N'ISO 10383 Operating MIC', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (206, 206, N'Transactions held on behalf of clients', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (207, 207, N'Date of report submission', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (208, 208, N'Report reference Number', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (209, 209, N'Date of the trading day of the reported position', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (210, 210, N'report status', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (211, 211, N'SCB Booking Entity/Branch', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (212, 212, N'SCB Booking Entity/Branch', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (213, 213, N'SCB Booking Entity/Branch/LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (214, 214, N'Cpty LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (215, 215, N'Cpty National ID for Natural Persons', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (216, 216, N'Email ID of Position Holder', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (217, 217, N'SCB Booking Entity/Branch', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (218, 218, N'Cpty LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (219, 219, N'SCB Group Entity LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (220, 220, N'SCB Booking Entity/Branch/LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (221, 221, N'Cpty Parent LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (222, 222, N'Cpty National ID for Natural Persons', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (223, 223, N'Instrument ISIN', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (224, 224, N'Internal Instrument Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (225, 225, N'OTC ISIN', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (226, 226, N'Venue Product Code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (227, 227, N'Position Type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (228, 228, N'Internal Instrument Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (229, 229, N'TP Product Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (230, 230, N'Trade date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (231, 231, N'Maturity date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (232, 232, N'Spot Month Contract', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (233, 233, N'Quantity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (234, 234, N'Delta equivalent position quantity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (235, 235, N'TP Product Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (236, 236, N'Buyer/Seller Indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (237, 237, N'Long/Short Indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (238, 238, N'Indicator of whether the position is risk reducing in relation to commercial activity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (239, 239, N'Instrument identification code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (240, 240, N'instrument Full name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (241, 241, N'Instrument classification code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (242, 242, N'Commodities derivative indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (243, 243, N'TP System Venue ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (244, 244, N'Venue LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (245, 245, N'Trading venue', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (246, 246, N'Financial Instrument short name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (247, 247, N'Request for admission to trading by issuer', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (248, 248, N'No of Client Orders Aggregated if available', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (249, 249, N'Date for approval of the admission to trading', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (250, 250, N'Date of request for admission to trading', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (251, 251, N'Date of admission to trading or date of first trade', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (252, 252, N'Termination date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (253, 253, N'Notional Currency 1', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (254, 254, N'Total issued nominal amount', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (255, 255, N'Maturity date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (256, 256, N'Currency of nominal value', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (257, 257, N'Nominal value per unit', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (258, 258, N'Minimum traded value', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (259, 259, N'Fixed Rate', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (260, 260, N'Floating rate index ISIN', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (261, 261, N'Floating rate index name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (262, 262, N'Term of the index/benchmark of a floating rate bond', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (263, 263, N'Basis Point Spread', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (264, 264, N'Seniority of the bond', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (265, 265, N'Expiry date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (266, 266, N'Price Multiplier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (267, 267, N'Underlying instrument code', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (268, 268, N'Underlying Issuer LEI', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (269, 269, N'Underlying index name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (270, 270, N'Term of the underlying index', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (271, 271, N'Option Type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (272, 272, N'Strike Price', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (273, 273, N'Strike price currency', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (274, 274, N'Option exercise style', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (275, 275, N'Delivery Type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (276, 276, N'Asset Class Base Product Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (277, 277, N'Asset Class Sub product Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (278, 278, N'Asset Class Further Sub product Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (279, 279, N'Trading Venue Transaction type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (280, 280, N'Comm. Deriv. Price Provider', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (281, 281, N'Float Index Name of Leg 1', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (282, 282, N'Float Index Name of Leg 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (283, 283, N'Tenor/Term of Contract of Leg 1', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (284, 284, N'Tenor/Term of Contract of Leg 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (285, 285, N'Notional currency 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (286, 286, N'Fixed rate of Leg 1', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (287, 287, N'Fixed rate of Leg 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (288, 288, N'Floating rate of Leg 1', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (289, 289, N'Floating rate of Leg 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (290, 290, N'IR Term of contract of Leg 1', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (291, 291, N'IR Term of contract of Leg 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (292, 292, N'Notional currency 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (293, 293, N'Notional currency for FX', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (294, 294, N'Name and designation of the client', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (295, 295, N'Name and designation of any relevant person acting on behalf of the client', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (296, 296, N'A designation to identify the trader (Trader ID) responsible within the investment firm for the investment decision', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (297, 297, N'A designation to identify the algorithm (Algo ID) responsible within the investment firm for the investment decision', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (298, 298, N'SCB Internal Unique ID - Transaction reference Number', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (299, 299, N'A designation to identify the order (Order ID)', NULL)
GO
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (300, 300, N'Venue order id', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (301, 301, N'The identification code of the order assigned by the trading venue upon receipt of the file', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (302, 302, N'Block order indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (303, 303, N'No of Client Orders Aggregated if available', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (304, 304, N'Venue', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (305, 305, N'The name and other designation of the person to whom the order was transmitted', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (306, 306, N'Designation to identify the Seller and the Buyer', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (307, 307, N'Trading capacity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (308, 308, N'A designation to identify the Trader (Trader ID) responsible for the execution', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (309, 309, N'A designation to identify the algorithm (Algo ID) responsible within the investment firm for the investment decision', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (310, 310, N'B/S indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (311, 311, N'Instrument identification', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (312, 312, N'Ultimate underlying', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (313, 313, N'Put/Call identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (314, 314, N'Strike Price', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (315, 315, N'Up-front payment', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (316, 316, N'Delivery type', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (317, 317, N'Option style', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (318, 318, N'Maturity date', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (319, 319, N'Unit price and price notation', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (320, 320, N'Price', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (321, 321, N'Price multiplier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (322, 322, N'Currency 1', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (323, 323, N'Currency 2', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (324, 324, N'Remaining quantity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (325, 325, N'Modified quantity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (326, 326, N'Executed quantity', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (327, 327, N'Trading date time', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (328, 328, N'Transmitted date time', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (329, 329, N'Received date time', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (330, 330, N'Additional messages from Trading Venue', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (331, 331, N'Additional comments from Trading Venue', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (332, 332, N'Order Sequence', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (333, 333, N'Short selling flag', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (334, 334, N'SSR exemption flag', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (335, 335, N'Waiver indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (336, 336, N'Warnings on suitability and appropriateness', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (337, 337, N'Communication medium', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (338, 338, N'Communication identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (339, 339, N'Name of the recording system', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (340, 340, N'Counterparty/client identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (341, 341, N'Counterparty/client Name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (342, 342, N'Communication date time', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (343, 343, N'Clearing Status', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (344, 344, N'Give-Up/Give-In Indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (345, 345, N'Trade Novation flag', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (346, 346, N'TP Instrument traded usage', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (347, 347, N'Identifier for the transactions for which prices calculated over multiple instances', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (348, 348, N'Allocation Trade ID/Identifiers', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (349, 349, N'TWAP/VWAP Indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (350, 350, N'Linkage of Block and Allocation', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (351, 351, N'Package/Structure ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (352, 352, N'No of Components in the Package/Structure', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (353, 353, N'Identifier for the transactions that can be executed only as a single lot', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (354, 354, N'Identifier for the transactions executed for transfer of ownership of instruments traded', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (355, 355, N'Transfer Ownership Flag', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (356, 356, N'Securities delivery flag', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (357, 357, N'Securities financing transaction indicator', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (358, 358, N'Identifier for the transaction is carried out under the rules or procedures of a trading venue', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (359, 359, N'Identifier for the transactions where the current market price sint the driver for the transaction price', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (360, 360, N'Clearing Mandatory flag', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (361, 361, N'Client Clearing flag', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (362, 362, N'Client Clearing Broker ID', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (363, 363, N'Client Clearing Counterparty', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (364, 364, N'Clearing Mandatory Jurisdiction', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (365, 365, N'CCP Name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (366, 366, N'Exchange Name', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (367, 367, N'Give-Up/Give-In Counterparty (Prime Broker) Identifier', NULL)
INSERT [dbo].[NamedBankingProductAttribute] ([id], [BPAID], [Description], [section]) VALUES (368, 368, N'Give-Up/Give-In Counterparty (Prime broker) Name', NULL)
SET IDENTITY_INSERT [dbo].[NamedBankingProductAttribute] OFF





update [NamedBankingProductAttribute] set section = 's1' where id between 1 and 10;
update [NamedBankingProductAttribute] set section = 's2' where id between 11 and 20;
update [NamedBankingProductAttribute] set section = 's3' where id between 21 and 30;
update [NamedBankingProductAttribute] set section = 's4' where id between 31 and 40;
update [NamedBankingProductAttribute] set section = 's5' where id between 41 and 50;
update [NamedBankingProductAttribute] set section = 's6' where id between 51 and 60;
update [NamedBankingProductAttribute] set section = 's7' where id between 61 and 70;
update [NamedBankingProductAttribute] set section = 's8' where id between 71 and 80;
update [NamedBankingProductAttribute] set section = 's9' where id between 81 and 90;
update [NamedBankingProductAttribute] set section = 's10' where id between 91 and 100;

